name: Code Linting Workflow

on:
  workflow_call: 

jobs:
  lint:
   runs-on: self-hosted
   strategy:
     matrix:
       node-version: [ "20", "22", "24" ]
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Setup nodejs ${{ matrix.node-version}}
       uses: actions/setup-node@v6
       with:
         node-version: ${{ matrix.node-version }}
     - name: install dependencies
       run: npm i
     - name: Run Linter
       run: npx eslint "backend/*.js" "frontend/*.js"
     - name: Run Dependencies Check
       run: |
         npm audit
         npm audit fix
