name: Code Linting Workflow

on:
  push:
    branches: main
  workflow_dispatch: 

jobs:
  lint:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [ "20", "22", "24" ]
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Setup nodejs ${{ matrix.node-version}}
       uses: actions/setup-node@v6
       with:
         node-version: ${{ matrix.node-version }}
     - name: install dependencies
       run: npm i
     - name: Run Linter
       run: npx eslint "backend/*.js" "frontend/*.js" --format json --output-file eslint-report.json
       continue-on-error: true
     - name: Save JSON for later
       uses: actions/upload-artifact@v4
       with:
        name: eslint-raw-results
        path: eslint-report-${{matrix.node-version}}}.json
     - name: Run Dependencies Check
       run: |
         npm audit
         npm audit fix
