name: Deployment to server

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install docker-compose-v2 -y
      - name: Run the container
        run: |
          docker compose down && docker compose up -d --build --force-recreate --pull always
        env:
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{vars.DB_NAME}}
          DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
          DB_HOST: ${{vars.DB_HOST}}
          PORT: ${{vars.PORT}}
          DB_USER: ${{vars.DB_USER}}
      - name: Keep the runner active
        run: |
          sleep 1800
          curl http://localhost:3000
          docker ps
      - name: Setup Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared@v2

      - name: Start Tunnel
        run: |
          # Start the tunnel in the background
          cloudflared tunnel --url http://localhost:3000 > tunnel.log 2>&1 &
    
          # Wait for the URL to appear in the logs (up to 30 seconds)
          timeout 30s bash -c 'until grep -o "https://.*\.trycloudflare\.com" tunnel.log; do sleep 1; done' > url.txt
    
          # Print the URL so it's visible in the Action logs
          cat url.txt
 
