name: Deployment to server

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Check version of Docker Compose
        run: |
           docker --version
           docker compose version
      - name: Run the container
        run: |
          docker compose down && docker compose up -d --build --force-recreate --pull always
        env:
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{vars.DB_NAME}}
          DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
          DB_HOST: ${{vars.DB_HOST}}
          PORT: ${{vars.PORT}}
          DB_USER: ${{vars.DB_USER}}
      - name: Setup Cloudflare Tunnel
        id: cloudflare_tunnel
        uses: AnimMouse/setup-cloudflared@v2
        with:
          url: http://localhost:3000
      - name: Use the Public URL
        run: |
          echo "Your app is live at: ${{ steps.cloudflare_tunnel.outputs.url }}"
      - name: Keep the runner active
        run: sleep 1800
 
