name: Dockerfile Lint

on: 
  workflow_dispatch:
  workflow_call: 

jobs:
  dockerfile-lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  
